platform:ios, '7.0'

pod 'AFNetworking', '~> 2.6.3'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'UMengSocial', '~> 4.3'
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'AVOSCloudCrashReporting'
pod 'FMDB'
pod 'JSBadgeView', '1.4.1'
pod 'iVersion', '1.11.4'
pod 'iRate', '1.11.4'
pod 'YYModel'
pod 'FSCalendar'
pod 'MJExtension'
pod 'MWPhotoBrowser', '~> 2.1.1'
pod 'BaiduMapKit'
pod 'JZNavigationExtension'
pod 'CXPhotoBrowser'
