platform:ios, '7.0'

pod 'AFNetworking', '~> 2.6.3'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'UMengSocial', '~> 4.3'
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'FMDB'
pod 'JSBadgeView', '1.4.1'
pod 'YYModel'
pod 'FSCalendar'
pod 'MJExtension'
pod 'MWPhotoBrowser', '~> 2.1.1'
pod 'iVersion'