platform:ios, '7.0'

pod 'AFNetworking', '~> 2.6.3'
pod 'YYModel'
pod 'SDWebImage'
pod 'pop'
pod 'M13ProgressSuite'
pod 'M13BadgeView'
pod 'MJRefresh'
pod 'ReactiveCocoa'
pod 'JSONModel'
pod 'MBProgressHUD'
pod 'MagicalRecord'
pod 'iCarousel'
pod 'YYText'
